sudo: required
language: python
cache: pip
python:
    - "2.7"
services:
    - redis-server
install:
    - pip install --no-use-wheel lxml
    - pip install --allow-all-external -e .[all,test]
    - pip install coveralls
script:
    - coverage run setup.py test
after_success:
    - coverage combine
    - coveralls
